server:
  port: 8080

jwt:
  user:
    issuer: "RecoTrackAPI - Service"
    audience: "RecoTrackWeb - Client"
    clock-skew-seconds: 0

  service:
    issuer: "RecoTrackAPI - Service"
    audience: "RecoTrackAPI - Email-Service"
    clock-skew-seconds: 0

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
