# src/main/resources/application.yml
security:
  jwt:
    issuer: email-service
    audience: email-clients
    secret: ""

  clients:
    allowed:
      - client-a
      - client-b

  dev:
    enabled: false
    token : dev-token-for-swagger

springdoc:
  swagger-ui:
    path: /api-docs/swagger-ui.html
