server:
  port: 8080

jwt:
  user:
    secret: ${JWT_USER_SECRET}
    issuer: "RecoTrackAPI - Service"
    audience: "RecoTrackWeb - Client"
    clock-skew-seconds: 0

  service:
    secret: ${JWT_SERVICE_SECRET}
    issuer: "RecoTrackAPI - Service"
    audience: "RecoTrackAPI - Email-Service"
    clock-skew-seconds: 0

spring:
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_SMTP_USERNAME}
    password: ${BREVO_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
